version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/pokemon
permissions:
  - object: /home/ubuntu/www
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: IaC/scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: IaC/scripts/install_os_dependencies.sh
      timeout: 6000
      runas: root
    - location: IaC/scripts/install_python_dependencies.sh
      timeout: 6000
      runas: root
    - location: IaC/scripts/migrate.sh
      timeout: 6000
      runas: ubuntu
    - location: IaC/scripts/add_app_service.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: IaC/scripts/start_application.sh
      timeout: 6000
      runas: ubuntu

#  ApplicationStop:
#    - location: IaC/scripts/stop_application.sh
#      timeout: 6000
#      runas: ubuntu