# Generated by Django 3.0.7 on 2020-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type_1', models.CharField(max_length=63)),
                ('type_2', models.CharField(max_length=63)),
                ('total', models.CharField(max_length=63)),
                ('hp', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('sp_atk', models.PositiveSmallIntegerField()),
                ('sp_def', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('generation', models.CharField(max_length=3)),
                ('legendary', models.BooleanField()),
            ],
        ),
    ]
